import React, { createContext, useContext, useState } from 'react';

export type LangCode = 'EN' | 'ES' | 'FR' | 'DE' | 'JP';

// ─── Translation Dictionary ───────────────────────────────────────────────────

const translations = {
  EN: {
    // Navbar
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Contact',
    'nav.userDashboard': 'User Dashboard',
    'nav.admin': 'Admin',
    'nav.getStarted': 'Get Started',

    // Hero
    'hero.badge': 'Accepting New Projects for 2024',
    'hero.titleLine1': 'We Build',
    'hero.titleLine2': 'Digital Excellence',
    'hero.subtitle': 'The agency for forward-thinking brands. We combine AI-driven development with award-winning design to build products that scale.',
    'hero.startProject': 'Start Your Project',
    'hero.viewWork': 'View Our Work',

    // Home – Services section
    'home.servicesTitle': 'Services designed for growth',
    'home.servicesSubtitle': 'We provide end-to-end solutions to help you launch and scale your digital products.',
    'home.webDevTitle': 'Web Development',
    'home.webDevDesc': 'High-performance web applications built with Next.js and React. Scalable, secure, and SEO-optimized.',
    'home.uiuxTitle': 'UI/UX Design',
    'home.uiuxDesc': 'User-centric design that converts. We create intuitive interfaces that users love to interact with.',
    'home.aiTitle': 'AI Integration',
    'home.aiDesc': 'Leverage the power of LLMs and AI to automate workflows and enhance user experience.',

    // Home – Why Choose Us
    'whyUs.titleLine1': 'Why forward-thinking companies',
    'whyUs.titleLine2': 'choose us',
    'whyUs.description': "We're not just a dev shop. We're your strategic partner in building digital products that stand out. Our AI-driven approach ensures faster delivery without compromising quality.",
    'whyUs.point1': 'AI-First Development Approach',
    'whyUs.point2': 'Rapid Prototyping & Iteration',
    'whyUs.point3': 'Enterprise-Grade Security',
    'whyUs.point4': '24/7 Support & Maintenance',
    'whyUs.scheduleConsult': 'Schedule a Consultation',

    // Why Choose Us – feature cards
    'feature.support': '24/7 Support',
    'feature.supportDesc': 'Always here when you need us.',
    'feature.security': 'Top Security',
    'feature.securityDesc': 'Enterprise-grade protection.',
    'feature.team': 'Expert Team',
    'feature.teamDesc': 'Top 1% of global talent.',
    'feature.delivery': 'Fast Delivery',
    'feature.deliveryDesc': '2x faster than competitors.',
    'feature.scalable': 'Scalable Arch',
    'feature.scalableDesc': 'Built to grow with you.',
    'feature.stack': 'Modern Stack',
    'feature.stackDesc': 'Latest technologies used.',

    // Home – FAQ
    'faq.sectionTitle': 'Frequently Asked Questions',
    'faq.q1': 'How long does a typical project take?',
    'faq.a1': 'Project timelines vary based on complexity. A standard business website typically takes 4-6 weeks, while a complex web application can take 3-6 months. We provide detailed timelines during our initial consultation.',
    'faq.q2': 'Do you offer post-launch support?',
    'faq.a2': 'Yes, we offer comprehensive maintenance and support packages to ensure your digital product remains secure, up-to-date, and performing optimally after launch.',
    'faq.q3': 'What technologies do you specialize in?',
    'faq.a3': 'We specialize in modern JavaScript ecosystems including React, Next.js, Node.js, and React Native. We also have deep expertise in cloud infrastructure (AWS/Google Cloud) and AI integration.',
    'faq.q4': 'How do you handle project pricing?',
    'faq.a4': 'We offer both fixed-price contracts for well-defined projects and time-and-materials engagements for evolving products. Our pricing is transparent with no hidden fees.',

    // Process section
    'process.badge': 'Our Process',
    'process.title': 'How We Build Excellence',
    'process.subtitle': 'A battle-tested workflow refined over hundreds of projects — from discovery to deployment.',

    // Process steps
    'process.step1.title': 'Discovery & Strategy',
    'process.step1.desc': 'We dive deep into your business goals to create a roadmap for success.',
    'process.step1.d1': 'Market Analysis',
    'process.step1.d2': 'User Personas',
    'process.step1.d3': 'Technical Feasibility',
    'process.step2.title': 'UX/UI Design',
    'process.step2.desc': 'Crafting intuitive interfaces that look stunning and function seamlessly.',
    'process.step2.d1': 'Wireframing',
    'process.step2.d2': 'High-Fidelity Mockups',
    'process.step2.d3': 'Interactive Prototypes',
    'process.step3.title': 'Development',
    'process.step3.desc': 'Building robust, scalable applications using modern technologies.',
    'process.step3.d1': 'Clean Code Architecture',
    'process.step3.d2': 'API Integration',
    'process.step3.d3': 'Performance Optimization',
    'process.step4.title': 'Quality Assurance',
    'process.step4.desc': 'Rigorous testing to ensure a bug-free, smooth user experience.',
    'process.step4.d1': 'Automated Testing',
    'process.step4.d2': 'Cross-Browser Checks',
    'process.step4.d3': 'Security Audits',
    'process.step5.title': 'Launch & Scale',
    'process.step5.desc': 'Deploying your product and monitoring its growth in the real world.',
    'process.step5.d1': 'CI/CD Pipelines',
    'process.step5.d2': 'Analytics Setup',
    'process.step5.d3': 'Post-Launch Support',

    // TransformCTA
    'cta.badge': 'Ready for takeoff?',
    'cta.titleLine1': 'Transform',
    'cta.titleLine2': 'Your Reality',
    'cta.description': "Join the visionaries who are reshaping the digital landscape. We build the infrastructure for your wildest ideas.",
    'cta.startProject': 'Start Your Project',
    'cta.viewCaseStudies': 'View Case Studies',

    // Footer
    'footer.letsBuild': "Let's build",
    'footer.theFuture': 'the future.',
    'footer.readyToTransform': "Ready to transform your digital presence? We're the partners you've been looking for.",
    'footer.startProject': 'Start a Project',
    'footer.available': 'Available for new projects',
    'footer.description': 'Crafting exceptional digital experiences through code, design, and strategy. Based in San Francisco, working globally.',
    'footer.copyright': 'Nabeel Agency. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookies Settings',
    'footer.madeWith': 'Made with',
    'footer.inCalifornia': 'in California',
    'footer.exploreTitle': 'Explore',
    'footer.emailTemplatesTitle': 'Email Templates',
    'footer.companyTitle': 'Company',
  },

  ES: {
    // Navbar
    'nav.services': 'Servicios',
    'nav.portfolio': 'Portafolio',
    'nav.contact': 'Contacto',
    'nav.userDashboard': 'Panel de Usuario',
    'nav.admin': 'Admin',
    'nav.getStarted': 'Comenzar',

    // Hero
    'hero.badge': 'Aceptando Nuevos Proyectos para 2024',
    'hero.titleLine1': 'Construimos',
    'hero.titleLine2': 'Excelencia Digital',
    'hero.subtitle': 'La agencia para marcas visionarias. Combinamos desarrollo impulsado por IA con diseño galardonado para crear productos escalables.',
    'hero.startProject': 'Iniciar Proyecto',
    'hero.viewWork': 'Ver Nuestro Trabajo',

    // Home – Services section
    'home.servicesTitle': 'Servicios diseñados para crecer',
    'home.servicesSubtitle': 'Ofrecemos soluciones de extremo a extremo para lanzar y escalar sus productos digitales.',
    'home.webDevTitle': 'Desarrollo Web',
    'home.webDevDesc': 'Aplicaciones web de alto rendimiento construidas con Next.js y React. Escalables, seguras y optimizadas para SEO.',
    'home.uiuxTitle': 'Diseño UI/UX',
    'home.uiuxDesc': 'Diseño centrado en el usuario que convierte. Creamos interfaces intuitivas que los usuarios adoran.',
    'home.aiTitle': 'Integración de IA',
    'home.aiDesc': 'Aprovecha el poder de los LLMs e IA para automatizar flujos de trabajo y mejorar la experiencia del usuario.',

    // Home – Why Choose Us
    'whyUs.titleLine1': 'Por qué las empresas visionarias',
    'whyUs.titleLine2': 'nos eligen',
    'whyUs.description': 'No somos solo un estudio de desarrollo. Somos tu socio estratégico en la construcción de productos digitales destacados. Nuestro enfoque basado en IA garantiza una entrega más rápida sin comprometer la calidad.',
    'whyUs.point1': 'Enfoque de Desarrollo IA-First',
    'whyUs.point2': 'Prototipado e Iteración Rápida',
    'whyUs.point3': 'Seguridad de Nivel Empresarial',
    'whyUs.point4': 'Soporte y Mantenimiento 24/7',
    'whyUs.scheduleConsult': 'Programar una Consulta',

    'feature.support': 'Soporte 24/7',
    'feature.supportDesc': 'Siempre aquí cuando nos necesites.',
    'feature.security': 'Seguridad Óptima',
    'feature.securityDesc': 'Protección de nivel empresarial.',
    'feature.team': 'Equipo Experto',
    'feature.teamDesc': 'Top 1% del talento global.',
    'feature.delivery': 'Entrega Rápida',
    'feature.deliveryDesc': '2x más rápido que la competencia.',
    'feature.scalable': 'Arquitectura Escalable',
    'feature.scalableDesc': 'Construido para crecer contigo.',
    'feature.stack': 'Stack Moderno',
    'feature.stackDesc': 'Últimas tecnologías utilizadas.',

    'faq.sectionTitle': 'Preguntas Frecuentes',
    'faq.q1': '¿Cuánto tiempo tarda un proyecto típico?',
    'faq.a1': 'Los plazos varían según la complejidad. Un sitio web empresarial estándar suele tardar 4-6 semanas, mientras que una aplicación web compleja puede tardar 3-6 meses.',
    'faq.q2': '¿Ofrecen soporte post-lanzamiento?',
    'faq.a2': 'Sí, ofrecemos paquetes completos de mantenimiento y soporte para garantizar que tu producto digital sea seguro, esté actualizado y funcione de manera óptima.',
    'faq.q3': '¿En qué tecnologías se especializan?',
    'faq.a3': 'Nos especializamos en ecosistemas modernos de JavaScript incluyendo React, Next.js, Node.js y React Native, además de infraestructura cloud e integración de IA.',
    'faq.q4': '¿Cómo manejan los precios de proyectos?',
    'faq.a4': 'Ofrecemos contratos de precio fijo para proyectos bien definidos y acuerdos por tiempo y materiales para productos en evolución. Nuestros precios son transparentes sin tarifas ocultas.',

    'process.badge': 'Nuestro Proceso',
    'process.title': 'Cómo Construimos la Excelencia',
    'process.subtitle': 'Un flujo de trabajo probado refinado en cientos de proyectos, desde el descubrimiento hasta el despliegue.',

    'process.step1.title': 'Descubrimiento y Estrategia',
    'process.step1.desc': 'Profundizamos en tus objetivos de negocio para crear una hoja de ruta hacia el éxito.',
    'process.step1.d1': 'Análisis de Mercado',
    'process.step1.d2': 'Personas de Usuario',
    'process.step1.d3': 'Viabilidad Técnica',
    'process.step2.title': 'Diseño UX/UI',
    'process.step2.desc': 'Creando interfaces intuitivas que se ven impresionantes y funcionan sin problemas.',
    'process.step2.d1': 'Wireframing',
    'process.step2.d2': 'Mockups de Alta Fidelidad',
    'process.step2.d3': 'Prototipos Interactivos',
    'process.step3.title': 'Desarrollo',
    'process.step3.desc': 'Construyendo aplicaciones robustas y escalables con tecnologías modernas.',
    'process.step3.d1': 'Arquitectura de Código Limpio',
    'process.step3.d2': 'Integración de API',
    'process.step3.d3': 'Optimización de Rendimiento',
    'process.step4.title': 'Control de Calidad',
    'process.step4.desc': 'Pruebas rigurosas para garantizar una experiencia de usuario fluida y sin errores.',
    'process.step4.d1': 'Pruebas Automatizadas',
    'process.step4.d2': 'Verificaciones Cross-Browser',
    'process.step4.d3': 'Auditorías de Seguridad',
    'process.step5.title': 'Lanzamiento y Escala',
    'process.step5.desc': 'Desplegando tu producto y monitoreando su crecimiento en el mundo real.',
    'process.step5.d1': 'Pipelines CI/CD',
    'process.step5.d2': 'Configuración de Analytics',
    'process.step5.d3': 'Soporte Post-Lanzamiento',

    'cta.badge': '¿Listo para despegar?',
    'cta.titleLine1': 'Transforma',
    'cta.titleLine2': 'Tu Realidad',
    'cta.description': 'Únete a los visionarios que están redefiniendo el panorama digital. Construimos la infraestructura para tus ideas más ambiciosas.',
    'cta.startProject': 'Iniciar Proyecto',
    'cta.viewCaseStudies': 'Ver Casos de Estudio',

    'footer.letsBuild': 'Construyamos',
    'footer.theFuture': 'el futuro.',
    'footer.readyToTransform': '¿Listo para transformar tu presencia digital? Somos los socios que buscabas.',
    'footer.startProject': 'Iniciar Proyecto',
    'footer.available': 'Disponible para nuevos proyectos',
    'footer.description': 'Creando experiencias digitales excepcionales a través de código, diseño y estrategia. Con sede en San Francisco, trabajando globalmente.',
    'footer.copyright': 'Nabeel Agency. Todos los derechos reservados.',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.cookies': 'Configuración de Cookies',
    'footer.madeWith': 'Hecho con',
    'footer.inCalifornia': 'en California',
    'footer.exploreTitle': 'Explorar',
    'footer.emailTemplatesTitle': 'Plantillas de Email',
    'footer.companyTitle': 'Empresa',
  },

  FR: {
    // Navbar
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Contact',
    'nav.userDashboard': 'Tableau de Bord',
    'nav.admin': 'Admin',
    'nav.getStarted': 'Commencer',

    // Hero
    'hero.badge': 'Acceptons de Nouveaux Projets pour 2024',
    'hero.titleLine1': 'Nous Créons',
    'hero.titleLine2': "L'Excellence Digitale",
    'hero.subtitle': "L'agence pour les marques visionnaires. Nous combinons le développement IA avec un design primé pour créer des produits qui évoluent.",
    'hero.startProject': 'Lancer Votre Projet',
    'hero.viewWork': 'Voir Nos Travaux',

    'home.servicesTitle': 'Services conçus pour la croissance',
    'home.servicesSubtitle': 'Nous fournissons des solutions de bout en bout pour lancer et faire évoluer vos produits numériques.',
    'home.webDevTitle': 'Développement Web',
    'home.webDevDesc': 'Applications web haute performance construites avec Next.js et React. Évolutives, sécurisées et optimisées SEO.',
    'home.uiuxTitle': 'Design UI/UX',
    'home.uiuxDesc': "Design centré sur l'utilisateur qui convertit. Nous créons des interfaces intuitives que les utilisateurs adorent.",
    'home.aiTitle': "Intégration IA",
    'home.aiDesc': "Exploitez la puissance des LLMs et de l'IA pour automatiser les flux de travail et améliorer l'expérience utilisateur.",

    'whyUs.titleLine1': 'Pourquoi les entreprises visionnaires',
    'whyUs.titleLine2': 'nous choisissent',
    'whyUs.description': "Nous ne sommes pas qu'un studio de développement. Nous sommes votre partenaire stratégique pour créer des produits numériques remarquables. Notre approche IA garantit une livraison plus rapide sans compromettre la qualité.",
    'whyUs.point1': "Approche Développement IA-First",
    'whyUs.point2': 'Prototypage et Itération Rapides',
    'whyUs.point3': 'Sécurité de Niveau Entreprise',
    'whyUs.point4': 'Support et Maintenance 24/7',
    'whyUs.scheduleConsult': 'Planifier une Consultation',

    'feature.support': 'Support 24/7',
    'feature.supportDesc': 'Toujours là quand vous en avez besoin.',
    'feature.security': 'Sécurité Optimale',
    'feature.securityDesc': 'Protection de niveau entreprise.',
    'feature.team': 'Équipe Experte',
    'feature.teamDesc': 'Top 1% des talents mondiaux.',
    'feature.delivery': 'Livraison Rapide',
    'feature.deliveryDesc': '2x plus rapide que la concurrence.',
    'feature.scalable': 'Architecture Scalable',
    'feature.scalableDesc': 'Construit pour évoluer avec vous.',
    'feature.stack': 'Stack Moderne',
    'feature.stackDesc': 'Dernières technologies utilisées.',

    'faq.sectionTitle': 'Questions Fréquentes',
    'faq.q1': 'Combien de temps dure un projet typique ?',
    'faq.a1': 'Les délais varient selon la complexité. Un site web professionnel standard prend généralement 4 à 6 semaines, tandis qu\'une application web complexe peut prendre 3 à 6 mois.',
    'faq.q2': 'Proposez-vous un support après lancement ?',
    'faq.a2': 'Oui, nous proposons des forfaits complets de maintenance et de support pour garantir que votre produit reste sécurisé, à jour et performant après le lancement.',
    'faq.q3': 'Dans quelles technologies vous spécialisez-vous ?',
    'faq.a3': 'Nous nous spécialisons dans les écosystèmes JavaScript modernes incluant React, Next.js, Node.js et React Native, ainsi que l\'infrastructure cloud et l\'intégration IA.',
    'faq.q4': 'Comment gérez-vous les tarifs de projets ?',
    'faq.a4': 'Nous proposons des contrats à prix fixe pour des projets bien définis et des engagements en régie pour des produits en évolution. Nos tarifs sont transparents, sans frais cachés.',

    'process.badge': 'Notre Processus',
    'process.title': "Comment Nous Construisons l'Excellence",
    'process.subtitle': 'Un flux de travail éprouvé affiné sur des centaines de projets, de la découverte au déploiement.',

    'process.step1.title': 'Découverte et Stratégie',
    'process.step1.desc': 'Nous plongeons dans vos objectifs commerciaux pour créer une feuille de route vers le succès.',
    'process.step1.d1': 'Analyse de Marché',
    'process.step1.d2': 'Personas Utilisateurs',
    'process.step1.d3': 'Faisabilité Technique',
    'process.step2.title': 'Design UX/UI',
    'process.step2.desc': "Créer des interfaces intuitives qui sont superbes et fonctionnent parfaitement.",
    'process.step2.d1': 'Wireframing',
    'process.step2.d2': 'Maquettes Haute Fidélité',
    'process.step2.d3': 'Prototypes Interactifs',
    'process.step3.title': 'Développement',
    'process.step3.desc': 'Construire des applications robustes et évolutives avec des technologies modernes.',
    'process.step3.d1': 'Architecture Code Propre',
    'process.step3.d2': 'Intégration API',
    'process.step3.d3': 'Optimisation des Performances',
    'process.step4.title': 'Assurance Qualité',
    'process.step4.desc': 'Tests rigoureux pour garantir une expérience utilisateur fluide et sans bugs.',
    'process.step4.d1': 'Tests Automatisés',
    'process.step4.d2': 'Vérifications Cross-Browser',
    'process.step4.d3': 'Audits de Sécurité',
    'process.step5.title': 'Lancement et Mise à l\'Échelle',
    'process.step5.desc': 'Déploiement de votre produit et suivi de sa croissance dans le monde réel.',
    'process.step5.d1': 'Pipelines CI/CD',
    'process.step5.d2': 'Configuration Analytics',
    'process.step5.d3': 'Support Post-Lancement',

    'cta.badge': 'Prêt pour le décollage ?',
    'cta.titleLine1': 'Transformez',
    'cta.titleLine2': 'Votre Réalité',
    'cta.description': 'Rejoignez les visionnaires qui redéfinissent le paysage numérique. Nous construisons l\'infrastructure pour vos idées les plus audacieuses.',
    'cta.startProject': 'Lancer Votre Projet',
    'cta.viewCaseStudies': "Voir les Études de Cas",

    'footer.letsBuild': 'Construisons',
    'footer.theFuture': 'le futur.',
    'footer.readyToTransform': 'Prêt à transformer votre présence numérique ? Nous sommes les partenaires que vous recherchez.',
    'footer.startProject': 'Démarrer un Projet',
    'footer.available': 'Disponible pour de nouveaux projets',
    'footer.description': 'Créer des expériences numériques exceptionnelles grâce au code, au design et à la stratégie. Basé à San Francisco, travaillant mondialement.',
    'footer.copyright': 'Nabeel Agency. Tous droits réservés.',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': "Conditions d'Utilisation",
    'footer.cookies': 'Paramètres des Cookies',
    'footer.madeWith': 'Fait avec',
    'footer.inCalifornia': 'en Californie',
    'footer.exploreTitle': 'Explorer',
    'footer.emailTemplatesTitle': "Modèles d'Email",
    'footer.companyTitle': 'Entreprise',
  },

  DE: {
    // Navbar
    'nav.services': 'Leistungen',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Kontakt',
    'nav.userDashboard': 'Benutzer-Dashboard',
    'nav.admin': 'Admin',
    'nav.getStarted': 'Loslegen',

    // Hero
    'hero.badge': 'Neue Projekte für 2024 werden angenommen',
    'hero.titleLine1': 'Wir Schaffen',
    'hero.titleLine2': 'Digitale Exzellenz',
    'hero.subtitle': 'Die Agentur für zukunftsorientierte Marken. Wir verbinden KI-gesteuerte Entwicklung mit preisgekröntem Design für skalierbare Produkte.',
    'hero.startProject': 'Projekt Starten',
    'hero.viewWork': 'Unsere Arbeit Ansehen',

    'home.servicesTitle': 'Leistungen für Wachstum',
    'home.servicesSubtitle': 'Wir bieten End-to-End-Lösungen, um Ihre digitalen Produkte zu launchen und zu skalieren.',
    'home.webDevTitle': 'Webentwicklung',
    'home.webDevDesc': 'Hochleistungs-Webanwendungen mit Next.js und React. Skalierbar, sicher und SEO-optimiert.',
    'home.uiuxTitle': 'UI/UX Design',
    'home.uiuxDesc': 'Nutzerzentriertes Design, das konvertiert. Wir erstellen intuitive Oberflächen, die Nutzer lieben.',
    'home.aiTitle': 'KI-Integration',
    'home.aiDesc': 'Nutzen Sie die Kraft von LLMs und KI, um Workflows zu automatisieren und die Nutzererfahrung zu verbessern.',

    'whyUs.titleLine1': 'Warum zukunftsorientierte Unternehmen',
    'whyUs.titleLine2': 'uns wählen',
    'whyUs.description': 'Wir sind nicht nur ein Dev-Shop. Wir sind Ihr strategischer Partner beim Aufbau herausragender digitaler Produkte. Unser KI-getriebener Ansatz gewährleistet schnellere Lieferung ohne Qualitätskompromisse.',
    'whyUs.point1': 'KI-First Entwicklungsansatz',
    'whyUs.point2': 'Schnelles Prototyping & Iteration',
    'whyUs.point3': 'Enterprise-Grade Sicherheit',
    'whyUs.point4': '24/7 Support & Wartung',
    'whyUs.scheduleConsult': 'Beratung Vereinbaren',

    'feature.support': '24/7 Support',
    'feature.supportDesc': 'Immer für Sie da, wenn Sie uns brauchen.',
    'feature.security': 'Top Sicherheit',
    'feature.securityDesc': 'Schutz auf Enterprise-Niveau.',
    'feature.team': 'Expertenteam',
    'feature.teamDesc': 'Top 1% der globalen Talente.',
    'feature.delivery': 'Schnelle Lieferung',
    'feature.deliveryDesc': '2x schneller als der Wettbewerb.',
    'feature.scalable': 'Skalierbare Architektur',
    'feature.scalableDesc': 'Gebaut, um mit Ihnen zu wachsen.',
    'feature.stack': 'Moderner Stack',
    'feature.stackDesc': 'Neueste Technologien eingesetzt.',

    'faq.sectionTitle': 'Häufig Gestellte Fragen',
    'faq.q1': 'Wie lange dauert ein typisches Projekt?',
    'faq.a1': 'Die Projektdauer variiert je nach Komplexität. Eine Standard-Unternehmenswebsite dauert typischerweise 4-6 Wochen, während eine komplexe Webanwendung 3-6 Monate in Anspruch nehmen kann.',
    'faq.q2': 'Bieten Sie Support nach dem Launch an?',
    'faq.a2': 'Ja, wir bieten umfassende Wartungs- und Supportpakete an, um sicherzustellen, dass Ihr digitales Produkt sicher, aktuell und optimal funktionsfähig bleibt.',
    'faq.q3': 'Auf welche Technologien sind Sie spezialisiert?',
    'faq.a3': 'Wir sind auf moderne JavaScript-Ökosysteme spezialisiert, einschließlich React, Next.js, Node.js und React Native, sowie Cloud-Infrastruktur und KI-Integration.',
    'faq.q4': 'Wie handhaben Sie die Projektpreise?',
    'faq.a4': 'Wir bieten sowohl Festpreisverträge für klar definierte Projekte als auch Zeit-und-Material-Engagements für sich entwickelnde Produkte an. Unsere Preise sind transparent ohne versteckte Gebühren.',

    'process.badge': 'Unser Prozess',
    'process.title': 'Wie Wir Exzellenz Aufbauen',
    'process.subtitle': 'Ein bewährter Workflow, verfeinert über Hunderte von Projekten – von der Entdeckung bis zur Bereitstellung.',

    'process.step1.title': 'Entdeckung & Strategie',
    'process.step1.desc': 'Wir tauchen tief in Ihre Geschäftsziele ein, um einen Fahrplan zum Erfolg zu erstellen.',
    'process.step1.d1': 'Marktanalyse',
    'process.step1.d2': 'Nutzer-Personas',
    'process.step1.d3': 'Technische Machbarkeit',
    'process.step2.title': 'UX/UI Design',
    'process.step2.desc': 'Intuitive Oberflächen gestalten, die beeindruckend aussehen und nahtlos funktionieren.',
    'process.step2.d1': 'Wireframing',
    'process.step2.d2': 'High-Fidelity Mockups',
    'process.step2.d3': 'Interaktive Prototypen',
    'process.step3.title': 'Entwicklung',
    'process.step3.desc': 'Robuste, skalierbare Anwendungen mit modernen Technologien entwickeln.',
    'process.step3.d1': 'Saubere Code-Architektur',
    'process.step3.d2': 'API-Integration',
    'process.step3.d3': 'Performance-Optimierung',
    'process.step4.title': 'Qualitätssicherung',
    'process.step4.desc': 'Rigoroses Testen für ein fehlerfreies, reibungsloses Nutzererlebnis.',
    'process.step4.d1': 'Automatisiertes Testen',
    'process.step4.d2': 'Cross-Browser-Prüfungen',
    'process.step4.d3': 'Sicherheitsaudits',
    'process.step5.title': 'Launch & Skalierung',
    'process.step5.desc': 'Ihr Produkt deployen und sein Wachstum in der realen Welt überwachen.',
    'process.step5.d1': 'CI/CD Pipelines',
    'process.step5.d2': 'Analytics-Einrichtung',
    'process.step5.d3': 'Post-Launch-Support',

    'cta.badge': 'Bereit zum Abheben?',
    'cta.titleLine1': 'Transformieren',
    'cta.titleLine2': 'Sie Ihre Realität',
    'cta.description': 'Schließen Sie sich den Visionären an, die die digitale Landschaft neu gestalten. Wir bauen die Infrastruktur für Ihre kühnsten Ideen.',
    'cta.startProject': 'Projekt Starten',
    'cta.viewCaseStudies': 'Fallstudien Ansehen',

    'footer.letsBuild': 'Lass uns',
    'footer.theFuture': 'die Zukunft bauen.',
    'footer.readyToTransform': 'Bereit, Ihre digitale Präsenz zu transformieren? Wir sind die Partner, die Sie gesucht haben.',
    'footer.startProject': 'Projekt Starten',
    'footer.available': 'Verfügbar für neue Projekte',
    'footer.description': 'Außergewöhnliche digitale Erfahrungen durch Code, Design und Strategie schaffen. Mit Sitz in San Francisco, weltweit tätig.',
    'footer.copyright': 'Nabeel Agency. Alle Rechte vorbehalten.',
    'footer.privacy': 'Datenschutzrichtlinie',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.cookies': 'Cookie-Einstellungen',
    'footer.madeWith': 'Gemacht mit',
    'footer.inCalifornia': 'in Kalifornien',
    'footer.exploreTitle': 'Erkunden',
    'footer.emailTemplatesTitle': 'E-Mail-Vorlagen',
    'footer.companyTitle': 'Unternehmen',
  },

  JP: {
    // Navbar
    'nav.services': 'サービス',
    'nav.portfolio': 'ポートフォリオ',
    'nav.contact': 'お問い合わせ',
    'nav.userDashboard': 'ユーザーダッシュボード',
    'nav.admin': '管理者',
    'nav.getStarted': '始めましょう',

    // Hero
    'hero.badge': '2024年の新プロジェクトを受付中',
    'hero.titleLine1': '私たちが創る',
    'hero.titleLine2': 'デジタルの卓越性',
    'hero.subtitle': '先進的なブランドのためのエージェンシー。AI駆動開発と受賞歴のあるデザインを組み合わせ、スケールする製品を構築します。',
    'hero.startProject': 'プロジェクトを開始',
    'hero.viewWork': '実績を見る',

    'home.servicesTitle': '成長のために設計されたサービス',
    'home.servicesSubtitle': 'デジタル製品のローンチとスケールを支援するエンドツーエンドのソリューションを提供します。',
    'home.webDevTitle': 'Web開発',
    'home.webDevDesc': 'Next.jsとReactで構築した高性能Webアプリケーション。スケーラブルで安全、SEO最適化済み。',
    'home.uiuxTitle': 'UI/UXデザイン',
    'home.uiuxDesc': 'コンバージョンするユーザー中心設計。ユーザーが愛する直感的なインターフェースを作成します。',
    'home.aiTitle': 'AI統合',
    'home.aiDesc': 'LLMとAIの力を活用してワークフローを自動化し、ユーザー体験を向上させます。',

    'whyUs.titleLine1': '先進的な企業が',
    'whyUs.titleLine2': '私たちを選ぶ理由',
    'whyUs.description': '私たちは単なる開発会社ではありません。卓越したデジタル製品を構築するための戦略パートナーです。AI駆動のアプローチにより、品質を損なわずに迅速なデリバリーを実現します。',
    'whyUs.point1': 'AIファースト開発アプローチ',
    'whyUs.point2': '迅速なプロトタイピングと反復',
    'whyUs.point3': 'エンタープライズグレードのセキュリティ',
    'whyUs.point4': '24/7サポートとメンテナンス',
    'whyUs.scheduleConsult': '相談を予約する',

    'feature.support': '24/7サポート',
    'feature.supportDesc': '必要な時にいつでもお応えします。',
    'feature.security': '最高のセキュリティ',
    'feature.securityDesc': 'エンタープライズグレードの保護。',
    'feature.team': '専門家チーム',
    'feature.teamDesc': 'グローバル上位1%の人材。',
    'feature.delivery': '迅速なデリバリー',
    'feature.deliveryDesc': '競合他社の2倍の速さ。',
    'feature.scalable': 'スケーラブルなアーキテクチャ',
    'feature.scalableDesc': 'あなたと共に成長できる設計。',
    'feature.stack': 'モダンなスタック',
    'feature.stackDesc': '最新技術を使用。',

    'faq.sectionTitle': 'よくある質問',
    'faq.q1': '一般的なプロジェクトにはどのくらいかかりますか？',
    'faq.a1': 'プロジェクトの期間は複雑さによって異なります。標準的なビジネスウェブサイトは通常4〜6週間、複雑なWebアプリケーションは3〜6ヶ月かかることがあります。',
    'faq.q2': 'ローンチ後のサポートはありますか？',
    'faq.a2': 'はい、ローンチ後もデジタル製品が安全で最新の状態を保ち、最適なパフォーマンスを維持できるよう、包括的なメンテナンスとサポートパッケージを提供しています。',
    'faq.q3': 'どのような技術を専門としていますか？',
    'faq.a3': 'React、Next.js、Node.js、React Nativeなどの最新JavaScriptエコシステム、クラウドインフラ（AWS/Google Cloud）、AI統合を専門としています。',
    'faq.q4': 'プロジェクトの料金はどのように決まりますか？',
    'faq.a4': '明確に定義されたプロジェクトには固定価格契約、進化する製品には実費精算での対応も可能です。隠れた費用なしの透明な料金体系です。',

    'process.badge': '私たちのプロセス',
    'process.title': 'いかに卓越性を構築するか',
    'process.subtitle': '数百のプロジェクトで磨き上げられた、発見からデプロイまでの実証済みワークフロー。',

    'process.step1.title': 'ディスカバリー & 戦略',
    'process.step1.desc': 'ビジネス目標を深く掘り下げ、成功へのロードマップを作成します。',
    'process.step1.d1': '市場分析',
    'process.step1.d2': 'ユーザーペルソナ',
    'process.step1.d3': '技術的実現可能性',
    'process.step2.title': 'UX/UIデザイン',
    'process.step2.desc': '見事に美しく、シームレスに機能する直感的なインターフェースを設計します。',
    'process.step2.d1': 'ワイヤーフレーミング',
    'process.step2.d2': 'ハイフィデリティモックアップ',
    'process.step2.d3': 'インタラクティブプロトタイプ',
    'process.step3.title': '開発',
    'process.step3.desc': '最新技術を使用した堅牢でスケーラブルなアプリケーションを構築します。',
    'process.step3.d1': 'クリーンコードアーキテクチャ',
    'process.step3.d2': 'API統合',
    'process.step3.d3': 'パフォーマンス最適化',
    'process.step4.title': '品質保証',
    'process.step4.desc': 'バグのない滑らかなユーザー体験を確保するための厳格なテスト。',
    'process.step4.d1': '自動テスト',
    'process.step4.d2': 'クロスブラウザチェック',
    'process.step4.d3': 'セキュリティ監査',
    'process.step5.title': 'ローンチ & スケール',
    'process.step5.desc': '製品をデプロイし、実世界での成長を監視します。',
    'process.step5.d1': 'CI/CDパイプライン',
    'process.step5.d2': 'アナリティクス設定',
    'process.step5.d3': 'ローンチ後サポート',

    'cta.badge': '離陸の準備はできましたか？',
    'cta.titleLine1': 'あなたの現実を',
    'cta.titleLine2': '変革しましょう',
    'cta.description': 'デジタル世界を再定義するビジョナリーに加わりましょう。あなたの最も大胆なアイデアのためのインフラを構築します。',
    'cta.startProject': 'プロジェクトを開始',
    'cta.viewCaseStudies': 'ケーススタディを見る',

    'footer.letsBuild': '未来を',
    'footer.theFuture': '一緒に作りましょう。',
    'footer.readyToTransform': 'デジタルプレゼンスを変革する準備はできていますか？私たちは探していたパートナーです。',
    'footer.startProject': 'プロジェクトを開始',
    'footer.available': '新プロジェクト受付中',
    'footer.description': 'コード、デザイン、戦略を通じた卓越したデジタル体験の創造。サンフランシスコ拠点、グローバルに活動。',
    'footer.copyright': 'Nabeel Agency. 全著作権所有。',
    'footer.privacy': 'プライバシーポリシー',
    'footer.terms': '利用規約',
    'footer.cookies': 'Cookie設定',
    'footer.madeWith': '作られました',
    'footer.inCalifornia': 'カリフォルニアで',
    'footer.exploreTitle': '探索',
    'footer.emailTemplatesTitle': 'メールテンプレート',
    'footer.companyTitle': '会社情報',
  },
} as const;

type TranslationKey = keyof typeof translations['EN'];

interface LanguageContextType {
  lang: LangCode;
  setLang: (lang: LangCode) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LangCode>(() => {
    return (localStorage.getItem('lang') as LangCode) || 'EN';
  });

  const setLang = (newLang: LangCode) => {
    setLangState(newLang);
    localStorage.setItem('lang', newLang);
  };

  const t = (key: TranslationKey): string => {
    const dict = translations[lang] as Record<string, string>;
    return dict[key] ?? (translations['EN'] as Record<string, string>)[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within a LanguageProvider');
  return ctx;
}
